services:
    DoubleStarSystems\Bundle\GoogleApiBundle\ClientFactory:
        arguments: []
    Google\Client:
        factory:   ['@DoubleStarSystems\Bundle\GoogleApiBundle\ClientFactory', createClient]
        arguments: []
